packages:
  - "apps/*"
  - "packages/*"

engineStrict: true
autoInstallPeers: true

overrides:
  sharp: 0.35.4
  deepmerge-ts: 8.0.2
  fast-uri: 3.1.6
  mysql2: 3.23.1

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  unrs-resolver: false
