import { demoReport, type DemoDimensionKey, type DemoIssueKey, type DemoTargetKey } from "@aurelis/database/demo";

import { localeCode, localize, type Locale } from "@/i18n/config";

type IssueContent = { title: string; evidence: string; recommendation: string };

export function getDemoContent(locale: Locale) {
  const copy = localize(locale, {
    en: {
      project: "Luxury AI landing page",
      modeLabel: "Sample data · Live audit not run",
      modeBody: "A curated, read-only example. Scores demonstrate the report structure and are not a live measurement of the example URL.",
      runEvaluation: "Evaluate my website",
      viewMethod: "Why this score",
      resultEyebrow: "Decision summary",
      resultSummary: "Strong technical quality, with brand language and one contrast state needing attention.",
      formula: "91.4 × 60% + 81.9 × 40%",
      formulaLabel: "Weighted score formula",
      gradeMeaning: "A− means the result is strong but still has material findings.",
      delta: "3.2-point sample difference",
      deltaBody: "This compares separate example targets, not improvement of the same page.",
      reliabilityBody: "Evidence coverage, strength, reviewer agreement, and reproducibility.",
      priorityAction: "Review first",
      findingsBody: "The highest-impact evidence appears before supporting charts.",
      openFinding: "Open finding",
      analysisEyebrow: "Supporting evidence",
      dimensionsTitle: "Dimension comparison",
      dimensionsBody: "Current sample and prior reference by quality dimension.",
      current: "Current sample",
      previous: "Prior reference",
      distributionTitle: "Sample score distribution",
      distributionBody: "Five different example targets. This is not a longitudinal improvement trend.",
      provenanceTitle: "Method and provenance",
      provenanceBody: "Inputs needed to understand and reproduce this sample calculation.",
      auditStatus: "Live audit status",
      notRun: "Not run",
      datasetVersion: "Dataset version",
      model: "Model",
      prompt: "Instruction version",
      rubric: "Evaluation standard",
      corpus: "Reference data",
      inputHash: "Input SHA-256",
      weights: "Score weights",
      reliabilityParts: "Reliability inputs",
      copyValue: "Copy value",
      copied: "Copied",
      sampleHistory: "Sample snapshots",
      sampleHistoryBody: "Read-only examples for interface verification. They do not link to real evaluation records.",
      target: "Target",
      date: "Date",
      score: "Score",
      status: "Status",
      sample: "Sample",
      issueEvidence: "Evidence",
      issueRecommendation: "Recommended action",
      backToDemo: "Back to sample report",
      runThisCheck: "Run this check on my website",
    },
    ja: {
      project: "高級ブランド向けAIランディングページ",
      modeLabel: "サンプルデータ · リアルタイム検査は未実行",
      modeBody: "レポート構成を確認するための読み取り専用サンプルです。表示中のURLを実際に測定した結果ではありません。",
      runEvaluation: "自分のサイトを評価する",
      viewMethod: "この点数の理由",
      resultEyebrow: "判断の要点",
      resultSummary: "技術品質は良好ですが、ブランド表現と一部のコントラストに改善余地があります。",
      formula: "91.4 × 60% + 81.9 × 40%",
      formulaLabel: "加重スコアの計算式",
      gradeMeaning: "A−は良好な結果ですが、対応すべき指摘が残っていることを示します。",
      delta: "サンプル間の差 3.2点",
      deltaBody: "同じページの改善ではなく、別々のサンプル対象を比較した値です。",
      reliabilityBody: "根拠の網羅性・強さ、判定の一致度、再現性から算出します。",
      priorityAction: "最初に確認",
      findingsBody: "影響の大きい根拠を、補助グラフより先に確認できます。",
      openFinding: "指摘を開く",
      analysisEyebrow: "判断を支えるデータ",
      dimensionsTitle: "項目別の比較",
      dimensionsBody: "現在のサンプルと参考値を品質項目ごとに比較します。",
      current: "現在のサンプル",
      previous: "参考値",
      distributionTitle: "サンプルスコアの分布",
      distributionBody: "5つの異なる対象を並べた例です。同一対象の改善推移ではありません。",
      provenanceTitle: "評価方法とデータ情報",
      provenanceBody: "サンプル計算の内容を理解し、確かめるための情報です。",
      auditStatus: "リアルタイム検査",
      notRun: "未実行",
      datasetVersion: "データ版",
      model: "モデル",
      prompt: "指示文の版",
      rubric: "評価基準",
      corpus: "参照データ",
      inputHash: "入力 SHA-256",
      weights: "スコア配分",
      reliabilityParts: "信頼性の内訳",
      copyValue: "値をコピー",
      copied: "コピーしました",
      sampleHistory: "サンプル一覧",
      sampleHistoryBody: "画面確認用の読み取り専用データです。実際の評価記録には移動しません。",
      target: "対象",
      date: "日付",
      score: "点数",
      status: "状態",
      sample: "サンプル",
      issueEvidence: "根拠",
      issueRecommendation: "推奨する対応",
      backToDemo: "サンプルレポートへ戻る",
      runThisCheck: "自分のサイトで確認する",
    },
    zh: {
      project: "高端品牌 AI 落地页",
      modeLabel: "示例数据 · 未执行实时审计",
      modeBody: "这是用于展示报告结构的只读示例，当前分数并非对示例网址进行实时测量所得。",
      runEvaluation: "评估我的网站",
      viewMethod: "为什么是这个分数",
      resultEyebrow: "决策摘要",
      resultSummary: "技术质量表现良好，但品牌措辞和一处对比度状态仍需处理。",
      formula: "91.4 × 60% + 81.9 × 40%",
      formulaLabel: "加权分数公式",
      gradeMeaning: "A− 表示整体表现较强，但仍有需要处理的重要问题。",
      delta: "示例间相差 3.2 分",
      deltaBody: "这里比较的是不同示例对象，并不代表同一页面持续提升。",
      reliabilityBody: "由证据完整度、证据强度、评审一致度和可复现性共同计算。",
      priorityAction: "优先检查",
      findingsBody: "先呈现影响最大的证据，再展示辅助图表。",
      openFinding: "查看问题",
      analysisEyebrow: "支持证据",
      dimensionsTitle: "维度对比",
      dimensionsBody: "按质量维度对比当前示例与参考值。",
      current: "当前示例",
      previous: "参考值",
      distributionTitle: "示例分数分布",
      distributionBody: "这里展示五个不同评估对象，并非同一对象的连续提升趋势。",
      provenanceTitle: "评估方法与数据来源",
      provenanceBody: "用于理解并复核本次示例计算的必要信息。",
      auditStatus: "实时审计状态",
      notRun: "未运行",
      datasetVersion: "数据集版本",
      model: "模型",
      prompt: "指令版本",
      rubric: "评估标准",
      corpus: "参考数据",
      inputHash: "输入 SHA-256",
      weights: "分数权重",
      reliabilityParts: "可信度组成",
      copyValue: "复制内容",
      copied: "已复制",
      sampleHistory: "示例快照",
      sampleHistoryBody: "这些只读记录仅用于验证界面，不会跳转到真实评估记录。",
      target: "评估对象",
      date: "日期",
      score: "分数",
      status: "状态",
      sample: "示例",
      issueEvidence: "证据",
      issueRecommendation: "建议操作",
      backToDemo: "返回示例报告",
      runThisCheck: "在我的网站运行此检查",
    },
  });

  const dimensions = localize<Record<DemoDimensionKey, string>>(locale, {
    en: { performance: "Performance", accessibility: "Accessibility", seo: "SEO", htmlQuality: "HTML quality", responsive: "Responsive", brandVoice: "Brand voice" },
    ja: { performance: "表示速度", accessibility: "アクセシビリティ", seo: "SEO", htmlQuality: "HTML品質", responsive: "画面対応", brandVoice: "ブランド表現" },
    zh: { performance: "性能", accessibility: "无障碍", seo: "SEO", htmlQuality: "HTML 质量", responsive: "响应式", brandVoice: "品牌语调" },
  });
  const severity = localize(locale, {
    en: { Critical: "Critical", High: "High", Medium: "Medium", Low: "Low" },
    ja: { Critical: "重大", High: "高", Medium: "中", Low: "低" },
    zh: { Critical: "严重", High: "高", Medium: "中", Low: "低" },
  });
  const issues = localize<Record<DemoIssueKey, IssueContent>>(locale, {
    en: {
      contrast: { title: "Primary action loses contrast in the lightest hero state", evidence: "Measured contrast drops below 4.5:1 in one captured state.", recommendation: "Use a stable dark text token or increase the action surface opacity." },
      vocabulary: { title: "Two claims exceed the approved confidence range", evidence: "“Guaranteed transformation” and “absolute results” do not appear in the reference data.", recommendation: "Replace absolute claims with qualified, evidence-led language." },
      heading: { title: "One heading level is skipped", evidence: "The methodology section moves directly from h2 to h4.", recommendation: "Use an h3 for the subsection heading." },
    },
    ja: {
      contrast: { title: "最も明るいヒーロー表示で主ボタンのコントラストが不足", evidence: "取得した1つの状態で、コントラスト比が4.5:1を下回っています。", recommendation: "文字色を安定した濃色にするか、ボタン背景の不透明度を上げます。" },
      vocabulary: { title: "2つの表現が承認済みの確信度を超えています", evidence: "「必ず変わる」「絶対的な成果」に相当する表現は参照データにありません。", recommendation: "断定を避け、根拠に基づく控えめな表現へ置き換えます。" },
      heading: { title: "見出しレベルが1段飛んでいます", evidence: "評価方法の章で h2 の次に h4 が使われています。", recommendation: "小見出しを h3 に変更します。" },
    },
    zh: {
      contrast: { title: "首屏最亮状态下，主按钮对比度不足", evidence: "在一个捕获状态中，实测对比度低于 4.5:1。", recommendation: "使用稳定的深色文字变量，或提高按钮底色的不透明度。" },
      vocabulary: { title: "两处宣传语超出已批准的可信表达范围", evidence: "“保证改变”和“绝对效果”没有出现在参考数据中。", recommendation: "改为有证据支持、带有适当限定的表达。" },
      heading: { title: "页面跳过了一个标题层级", evidence: "方法说明部分从 h2 直接跳到了 h4。", recommendation: "将该小节标题改为 h3。" },
    },
  });
  const targets = localize<Record<DemoTargetKey, string>>(locale, {
    en: { campaign: "Campaign landing", product: "Product overview", editorial: "Editorial concept", waitlist: "Waitlist page" },
    ja: { campaign: "キャンペーンページ", product: "製品紹介ページ", editorial: "編集コンセプト", waitlist: "事前登録ページ" },
    zh: { campaign: "活动落地页", product: "产品概览页", editorial: "编辑概念页", waitlist: "候补名单页" },
  });
  const date = new Intl.DateTimeFormat(localeCode(locale), { month: "short", day: "numeric", timeZone: "UTC" });

  return {
    ...copy,
    dimensions: demoReport.dimensions.map((item) => ({ ...item, dimension: dimensions[item.key] })),
    issues: demoReport.issues.map((item) => ({ ...item, ...issues[item.key], dimensionLabel: dimensions[item.dimension], severityLabel: severity[item.severity] })),
    trend: demoReport.trend.map((item) => ({ ...item, label: date.format(new Date(item.evaluatedAt)) })),
    recent: demoReport.recentEvaluations.map((item) => ({ ...item, targetLabel: targets[item.target], dateLabel: date.format(new Date(item.evaluatedAt)) })),
  };
}
